-- Two things to say to the section: with your name on it, and without.
--
-- ONE table, because a post and a confession differ in exactly one fact --
-- whether the class is told who wrote it -- and every other line of them is
-- identical: somebody's words, at a time, upvotable, hideable, never deleted.
-- Two tables would be two select policies, two insert policies, two grants,
-- two votes columns and two handlers kept in step by hand so that the day
-- somebody fixes a bug in one, the other keeps it.
--
-- The anonymity is NOT "the app does not send the name". The app is one
-- process and one mistake away from sending it, and this is the screen where
-- somebody will deliberately look. So the guarantee is a privilege: the
-- `authenticated` role is never granted select on author_id at all. A query
-- that asks for it -- from this server, from a second one written later, from
-- psql holding a member's claims -- is refused by Postgres before any policy
-- runs. What a member MAY read is byline_id, which the database itself
-- computes and which is null for every confession that ever exists.
--
-- The database still knows. It has to: somebody will post something vile and
-- an admin has to be able to deal with the person and not only the row. That
-- road is confession_author() below -- one function, admin-only, off the
-- screen everybody reads.
create table posts (
  id         uuid primary key default gen_random_uuid(),
  kind       text not null check (kind in ('feed', 'confession')),
  author_id  uuid not null references profiles(id),
  body       text not null check (length(btrim(body)) between 1 and 2000),
  -- Photos are the upload path that already exists: the phone mints a batch
  -- id, POSTs each photo to /upload with it, and names the batch here. No
  -- post_photos table, because materials already holds a file's subject, its
  -- uploader, its size and its bytes on disk, and a second one would hold a
  -- worse copy.
  batch_id   uuid,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  -- A confession is words alone. A photo is the one thing that identifies a
  -- person without naming them -- a hostel room, a handwriting, a friend in
  -- frame -- and the honest way to keep that promise is to have nowhere to
  -- put one.
  constraint posts_confessions_are_words_only
    check (kind = 'feed' or batch_id is null),
  -- The only author any member may read. Generated by the database rather
  -- than chosen by a query, so "we forgot the case statement" is not a state
  -- this column can be in.
  byline_id  uuid generated always as
             (case when kind = 'feed' then author_id end) stored
);

-- The one order either screen asks for: newest first, live only.
create index on posts (kind, created_at desc) where deleted_at is null;
create index on posts (batch_id) where batch_id is not null;

alter table posts enable row level security;

-- Everybody approved reads both walls. A hidden row stays readable to its
-- author for the reason 0025 spells out: Postgres checks the row an UPDATE
-- leaves behind against the select policy, so a policy that hides a row from
-- its own author is a policy under which nobody can hide anything. What the
-- screen shows is db_posts' business, and it asks for the live rows.
create policy "members read live posts" on posts for select
  using (is_approved()
         and (deleted_at is null or author_id = auth.uid() or is_admin()));

-- author_id = auth.uid() so nobody posts in somebody else's name -- and so
-- that a confession, whose author the class never sees, is still nailed to
-- the person who actually typed it.
create policy "members post" on posts for insert
  with check (is_approved() and author_id = auth.uid());

-- Taking your own words back, and an admin's reach over anybody's. A post is
-- not editable: words a hundred people have read must not become different
-- words under them.
create policy "your own posts, or any as admin" on posts for update
  using (is_admin() or author_id = auth.uid())
  with check (is_admin() or author_id = auth.uid());

-- No delete policy, on purpose, like announcements and doubts.

-- ---------------------------------------------------------------------------
-- A small number per day, counted by the database.
--
-- In the handler it would be a number one HTTP client honours. Here it is a
-- number every client honours, including the one somebody writes tonight with
-- a copied cookie -- which is the client this limit exists for.
--
-- SECURITY DEFINER because the count has to read author_id, and author_id is
-- the column the `authenticated` role is deliberately not granted. Execute is
-- revoked from everyone: a trigger fires on the table's own authority, so
-- nothing needs to be able to call this by name.
create function posts_daily_limit() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.kind = 'confession' and (
       select count(*) from posts
        where author_id = new.author_id and kind = 'confession'
          and created_at > now() - interval '1 day') >= 3 then
    -- Left as the default P0001 rather than a check violation: the
    -- handler has to tell "too fast" apart from "too long", and the
    -- two answer with different status codes.
    raise exception 'that is three confessions today — try again tomorrow';
  end if;
  return new;
end $$;

revoke execute on function posts_daily_limit() from public;

create trigger posts_daily_limit before insert on posts
  for each row execute function posts_daily_limit();

-- The deliberate route to an author, and the only one. An admin asks by id,
-- gets a name, and nothing about this is on a screen anybody else opens.
-- is_admin() is inside the function rather than in front of it, so a member
-- who reaches it gets null and not a name.
create function confession_author(p_id uuid) returns text
language sql stable security definer set search_path = public as $$
  select p.name from posts po join profiles p on p.id = po.author_id
   where po.id = p_id and po.kind = 'confession' and is_admin();
$$;

revoke execute on function confession_author(uuid) from public;
grant execute on function confession_author(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Privileges. Column-level here, which is the whole security story of this
-- file, so it is written out rather than left to `grant select on posts`.
--
-- The revoke is load-bearing in THIS repository and not in production:
-- backend/dev/migrate.py sets `alter default privileges ... grant all on
-- tables` before it applies anything, so a table created here arrives fully
-- granted and a column grant added on top of that would guard nothing. The
-- revoke puts the test database back into the state production starts in.
revoke all on posts from authenticated;
grant select (id, kind, body, batch_id, byline_id, deleted_at, created_at)
  on posts to authenticated;
grant insert (kind, author_id, body, batch_id) on posts to authenticated;
-- Hiding is the only write after the fact; nothing else about a post changes.
grant update (deleted_at) on posts to authenticated;

-- ---------------------------------------------------------------------------
-- Posts are upvoted with the votes table the notes and the doubts already
-- use, for the reasons 0025 gives at length. A third column, not a third
-- table -- and the two-way check becomes a three-way one.
alter table votes add column post_id uuid references posts(id) on delete cascade;
alter table votes drop constraint votes_one_thing;
alter table votes add constraint votes_one_thing
  check (num_nonnulls(material_id, doubt_id, post_id) = 1);
create unique index on votes (post_id, voter_id) where post_id is not null;

-- 0022's rule, for the third column: agreeing with yourself is not the class
-- agreeing with you.
--
-- It is a trigger and not a line in the vote policy, and that is forced by the
-- column grants above. A policy's subquery is checked against the CALLER's
-- privileges, so `select 1 from posts where author_id = voter_id` inside the
-- policy would be "permission denied for table posts" for every member -- and
-- granting author_id back to make it work would give away the whole feature.
--
-- A SECURITY DEFINER function called from the policy has the same problem
-- from the other side: anything a policy can call, a member can call, and
-- `select post_is_by(<confession>, <each of a hundred and ten ids>)` is the
-- author in a hundred and ten guesses. A trigger is callable by nobody and
-- fires on the table's own authority, so it is the one shape that both
-- enforces the rule and keeps the column shut.
--
-- It raises insufficient_privilege on purpose: that is the class of error the
-- vote handler already turns into "you cannot upvote your own", so the same
-- refusal reads the same way for an upload, an answer and a post.
create function votes_not_your_own_post() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.post_id is not null and exists (
       select 1 from posts where id = new.post_id and author_id = new.voter_id)
  then
    raise exception 'you cannot upvote your own post'
      using errcode = 'insufficient_privilege';
  end if;
  return new;
end $$;

revoke execute on function votes_not_your_own_post() from public;

create trigger votes_not_your_own_post before insert on votes
  for each row execute function votes_not_your_own_post();

-- The other two stay where they were, unchanged: materials and doubts are
-- tables a member may read in full, so a policy subquery over them is a
-- subquery the caller is allowed to run.
drop policy "vote as yourself" on votes;
create policy "vote as yourself" on votes for insert
  with check (
    is_approved() and voter_id = auth.uid()
    and not exists (select 1 from materials m
                     where m.id = material_id and m.uploader_id = voter_id)
    and not exists (select 1 from doubts d
                     where d.id = doubt_id and d.author_id = voter_id)
  );
